- hosts: vpn-exit
  become: true
  roles:
    - role: docker
      tags: ['docker']

- hosts: vpn_nodes
  become: true
  roles:
    - role: udp2raw
      tags: ['udp2raw']
    - role: firewall
      tags: ['firewall']